# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocurlAT190 < Formula
  desc "protoCURL is cURL for Protobuf: The command-line tool for interacting with Protobuf over HTTP REST endpoints using human-readable text formats."
  homepage "https://gitlab.com/qaware/protocurl"
  version "1.9.0-rc"
  license "MIT"

  depends_on "curl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qaware/protocurl/releases/v1.9.0-rc/protocurl_1.9.0-rc_darwin_amd64.zip"
      sha256 "bb28baba4ba1013bee325be5a0a9e15776f724e82f8cd53d70fa41426d0f203e"

      def install
        bin.install "protocurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qaware/protocurl/releases/v1.9.0-rc/protocurl_1.9.0-rc_darwin_arm64.zip"
      sha256 "63f61e78e5cdf24501000e33d66f45488a04f2b135d636d6b31b51afb4cf919f"

      def install
        bin.install "protocurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qaware/protocurl/releases/v1.9.0-rc/protocurl_1.9.0-rc_linux_arm64.zip"
      sha256 "36dfec0181402150009ec331d5e8145162e9fc9965f1f91e87d85508809a9101"

      def install
        bin.install "protocurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qaware/protocurl/releases/v1.9.0-rc/protocurl_1.9.0-rc_linux_amd64.zip"
      sha256 "5cf7384281016a7cd5c73ec7d559602fc114ac1a3643499fa72cc849dae05823"

      def install
        bin.install "protocurl"
      end
    end
  end
end
