name: Update brew Aliases
run-name: Updating brew Aliases 🚀
on:
  push:
    branches:
      - main
jobs:
  update-alises:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install packages
        run: |
          # https://github.com/marketplace/actions/yq-portable-yaml-processor
          wget -q -O yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x yq
          sudo mv yq /usr/bin/yq
      - name: Parse Formulas
        run: .ci-scripts/parse-formulas.sh
      - name: Generate Aliases
        run: .ci-scripts/generate-aliases.sh
      - name: Commit & Push changes
        run: |
          git config --global user.name 'QAware Homebrew Bot'
          git config --global user.email 'qaware.homebrew.bot@qaware.de'
          git add Aliases
          git commit -m "chore: update Aliases"
          git push
