name: Update brew Aliases
run-name: Updating brew Aliases 🚀
on:
  push:
    branches:
      - main
    paths:
      - .ci-scripts/*
      - .shellcheckrc
      - .github/workflows/*
      - Formula/*.rb
      - README.md
jobs:
  update-alises:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install packages
        run: .ci-scripts/install-packages.sh

      - name: Parse Formulas 1
        run: .ci-scripts/parse-formulas.sh

      - name: Enforce Formula Policies
        run: .ci-scripts/enforce-formula-policies.sh

      - name: Parse Formulas 2
        run: .ci-scripts/parse-formulas.sh

      - name: Generate Aliases
        run: .ci-scripts/generate-aliases.sh

      - name: Update TOC
        run: .ci-scripts/update-toc.sh

      - name: Commit & Push changes
        env:
          GIT_AUTHOR_NAME: QAware Homebrew Bot
          GIT_AUTHOR_EMAIL: qaware.homebrew.bot@qaware.de
          GIT_COMMITTER_NAME: QAware Homebrew Bot
          GIT_COMMITTER_EMAIL: qaware.homebrew.bot@qaware.de
        run: .ci-scripts/commit-push.sh
