name: Update TOC
run-name: Update TOC 🚀
on:
  push:
    branches:
      - main
    paths:
      - .ci-scripts/*
      - .shellcheckrc
      - .github/workflows/*
      - Formula/*.rb
      - README.md
jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Update TOC
        uses: qaware/update-brew-tap-toc-action@main

      - name: Commit & Push changes
        env:
          GIT_AUTHOR_NAME: QAware Homebrew Bot
          GIT_AUTHOR_EMAIL: qaware.homebrew.bot@qaware.de
          GIT_COMMITTER_NAME: QAware Homebrew Bot
          GIT_COMMITTER_EMAIL: qaware.homebrew.bot@qaware.de
        run: .ci-scripts/commit-push.sh
